image: alpine/edge
secrets:
  - 81931c8c-4491-466a-aa6f-15ab82dbd962
environment:
  SRHT_REPO: anton
  GH_REPO: stlc
  GH_USER: syedtaz
tasks:
  - write-ssh-config: |
    cat <<_FILE >> ~/.ssh/config
    Host github.com
      IdentityFile ~/.ssh/id_rsa
      IdentitiesOnly yes
      BatchMode yes
      StrictHostKeyChecking no
    _FILE_
  - push-to-github: |
    cd ~/"${SRHT_REPO}"
    git remote set-head origin -d
    git remote add github "git@github.com:${GH_USER}/${GH_REPO}.git"
    git push --prune github '+refs/remotes/origin/*:refs/heads/*' '+refs/tags/*:refs/tags/*'